[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/glonlas/sff-pre-auth"
  GO111MODULE = "on"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/cmd/:splat'
  status = 200